env:  # Global defaults
  CIRRUS_CLONE_DEPTH: 1
  CIRRUS_LOG_TIMESTAMP: true
  MAKEJOBS: "-j10"
  TEST_RUNNER_PORT_MIN: "14000"  # Must be larger than 12321, which is used for the http cache. See https://cirrus-ci.org/guide/writing-tasks/#http-cache
  CI_FAILFAST_TEST_LEAVE_DANGLING: "1"  # Cirrus CI does not care about dangling processes and setting this variable avoids killing the CI script itself on error

# When a contributor maintains a fork of the repo, any pull request they make
# to their own fork, or to the main repository, will trigger two CI runs:
# one for the branch push and one for the pull request.
# This can be avoided by setting SKIP_BRANCH_PUSH=true as a custom env variable
# in Cirrus repository settings, accessible from
# https://cirrus-ci.com/github/my-organization/my-repository

# https://cirrus-ci.org/guide/tips-and-tricks/#sharing-configuration-between-tasks
filter_template: &FILTER_TEMPLATE
  # Allow forks to specify SKIP_BRANCH_PUSH=true and skip CI runs when a branch is pushed,
  # but still run CI when a PR is created.
  # https://cirrus-ci.org/guide/writing-tasks/#conditional-task-execution
  skip: $SKIP_BRANCH_PUSH == "true" && $CIRRUS_PR == ""
  stateful: false  # https://cirrus-ci.org/guide/writing-tasks/#stateful-tasks

base_template: &BASE_TEMPLATE
  << : *FILTER_TEMPLATE
  merge_base_script:
    # Require git (used in fingerprint_script).
    - git --version || ( apt-get update && apt-get install -y git )
    - if [ "$CIRRUS_PR" = "" ]; then exit 0; fi
    - git fetch --depth=1 $CIRRUS_REPO_CLONE_URL "pull/${CIRRUS_PR}/merge"
    - git checkout FETCH_HEAD  # Use merged changes to detect silent merge conflicts
                               # Also, the merge commit is used to lint COMMIT_RANGE="HEAD~..HEAD"

global_task_template: &GLOBAL_TASK_TEMPLATE
  << : *BASE_TEMPLATE
  base_depends_built_cache:
    folder: "/ci_container_base/depends/built"
    fingerprint_script: echo $CIRRUS_TASK_NAME $(git rev-parse HEAD:depends)
  ccache_cache:
    folder: "/tmp/ccache_dir"
  timeout_in: 120m  # https://cirrus-ci.org/faq/#instance-timed-out
  ci_script:
    - ./ci/test_run_all.sh
  env:
    DANGER_RUN_CI_ON_HOST: "1"  # Containers will be discarded after the run, so there is no risk that the ci scripts modify the system
    CCACHE_MAXSIZE: "900M"  # Is this enough, but not too large???
  use_compute_credits: true

dockerfile_template: &DOCKERFILE_TEMPLATE
  cpu: 4
  memory: 16G
  greedy: true  # https://medium.com/cirruslabs/introducing-greedy-container-instances-29aad06dc2b4
  # https://cirrus-ci.org/guide/linux/#linux-containers
  # https://cirrus-ci.org/guide/docker-builder-vm/#dockerfile-as-a-ci-environment
  dockerfile: ci/test_imagefile

compute_credits_template: &CREDITS_TEMPLATE
  # https://cirrus-ci.org/pricing/#compute-credits
  # Only use credits for pull requests to the main repo
  use_compute_credits: $CIRRUS_REPO_FULL_NAME == 'bitcoin/bitcoin' && $CIRRUS_PR != ""

task:
  name: 'lint'
  << : *BASE_TEMPLATE
  container:
    dockerfile: ci/lint_imagefile
    cpu: 1
    memory: 1G
  # For faster CI feedback, immediately schedule the linters
  << : *CREDITS_TEMPLATE
  unshallow_script:
    - git fetch --unshallow --no-tags
  lint_script:
    - ./ci/lint_run.sh

task:
  name: 'tidy'
  << : *GLOBAL_TASK_TEMPLATE
  container:
    << : *DOCKERFILE_TEMPLATE
    docker_arguments:
      CI_IMAGE_NAME_TAG: ubuntu:24.04
      FILE_ENV: "./ci/test/00_setup_env_native_tidy.sh"

task:
  name: 'ARM, unit tests, no functional tests'
  << : *GLOBAL_TASK_TEMPLATE
  arm_container:  # Use arm64 worker to sidestep qemu and avoid a slow CI: https://github.com/bitcoin/bitcoin/pull/28087#issuecomment-1649399453
    << : *DOCKERFILE_TEMPLATE
    docker_arguments:
      CI_IMAGE_NAME_TAG: ubuntu:24.04
      FILE_ENV: "./ci/test/00_setup_env_arm.sh"

task:
  name: 'CentOS, depends, gui'
  << : *GLOBAL_TASK_TEMPLATE
  container:
    << : *DOCKERFILE_TEMPLATE
    docker_arguments:
      CI_IMAGE_NAME_TAG: quay.io/centos/centos:stream10
      FILE_ENV: "./ci/test/00_setup_env_native_centos.sh"

task:
  name: 'previous releases, depends DEBUG'
  << : *GLOBAL_TASK_TEMPLATE
  container:
    << : *DOCKERFILE_TEMPLATE
    docker_arguments:
      CI_IMAGE_NAME_TAG: ubuntu:22.04
      FILE_ENV: "./ci/test/00_setup_env_native_previous_releases.sh"

task:
  name: 'TSan, depends, gui'
  << : *GLOBAL_TASK_TEMPLATE
  container:
    << : *DOCKERFILE_TEMPLATE
    docker_arguments:
      CI_IMAGE_NAME_TAG: ubuntu:24.04
      FILE_ENV: "./ci/test/00_setup_env_native_tsan.sh"

task:
  name: 'MSan, depends'
  << : *GLOBAL_TASK_TEMPLATE
  container:
    << : *DOCKERFILE_TEMPLATE
    docker_arguments:
      CI_IMAGE_NAME_TAG: ubuntu:24.04
      FILE_ENV: "./ci/test/00_setup_env_native_msan.sh"

task:
  name: 'fuzzer,address,undefined,integer, no depends'
  << : *GLOBAL_TASK_TEMPLATE
  container:
    << : *DOCKERFILE_TEMPLATE
    docker_arguments:
      CI_IMAGE_NAME_TAG: ubuntu:24.04
      FILE_ENV: "./ci/test/00_setup_env_native_fuzz.sh"

task:
  name: 'multiprocess, i686, DEBUG'
  << : *GLOBAL_TASK_TEMPLATE
  container:
    << : *DOCKERFILE_TEMPLATE
    docker_arguments:
      CI_IMAGE_NAME_TAG: ubuntu:24.04
      FILE_ENV: "./ci/test/00_setup_env_i686_multiprocess.sh"

task:
  name: 'no wallet, libbitcoinkernel'
  << : *GLOBAL_TASK_TEMPLATE
  container:
    << : *DOCKERFILE_TEMPLATE
    docker_arguments:
      CI_IMAGE_NAME_TAG: debian:bookworm
      FILE_ENV: "./ci/test/00_setup_env_native_nowallet_libbitcoinkernel.sh"

task:
  name: 'macOS-cross, gui, no tests'
  << : *GLOBAL_TASK_TEMPLATE
  container:
    << : *DOCKERFILE_TEMPLATE
    docker_arguments:
      CI_IMAGE_NAME_TAG: ubuntu:24.04
      FILE_ENV: "./ci/test/00_setup_env_mac_cross.sh"
